#!/usr/bin/env python3

from pymongo import MongoClient, errors
from bson.json_util import dumps
import os

MONGOPASS = os.getenv('MONGOPASS')
uri = "mongodb+srv://cluster0.pnxzwgz.mongodb.net/sample_restaurants"
client = MongoClient(uri, username='nmagee', password=MONGOPASS, connectTimeoutMS=200, retryWrites=True)

#Creating new collection
sampler = client.sample_restaurants
restaurants = sampler.restaurants

#Inserting new records 
new_records = [
    {
      "address": {
      "building": "2780",
      "coord": [
        -73.982419,
        40.579505
      ],
      "street": "Stillwell Avenue",
      "zipcode": "11224"
    },
    "borough": "Brooklyn",
    "cuisine": "American",
    "name": "Riviera Caterer"
    },
    {
      "address": {
      "building": "7114",
      "coord": [
        -73.9068506,
        40.6199034
      ],
      "street": "Avenue U",
      "zipcode": "11234"
    },
    "borough": "Brooklyn",
    "cuisine": "Delicatessen",
    "name": "Wilken'S Fine Food"  
    }, 
    {
        "address": {
      "building": "1839",
      "coord": [
        -73.94826009,
        40.6408271
      ],
      "street": "Nostrand Avenue",
      "zipcode": "11226"
    },
    "borough": "Brooklyn",
    "cuisine": "Ice Cream, Gelato, Yogurt, Ices",
    "name": "Taste The Tropics Ice Cream"
    }, 
    {
        "address": {
      "building": "1007",
      "coord": [
        -73.856077,
        40.848447
      ],
      "street": "Morris Park Ave",
      "zipcode": "10462"
    },
    "borough": "Bronx",
    "cuisine": "Bakery",
    "name": "Morris Park Bake Shop"
    },
    {
        "address": {
      "building": "8825",
      "coord": [
        -73.98803827,
        40.57643124
      ],
      "street": "Astoria Boulevard",
      "zipcode": "11369"
    },
    "borough": "Queens",
    "cuisine": "American",
    "name": "Bronos On The Boulevard"
    }
]

restaurants.insert_many(new_records)

# Query that displays 3 documents 
get_three = restaurants.find({"borough" : "Brooklyn"}).limit(3)
print(dumps(get_three, indent=2))